### ISSUE TITLE
Illegal string offset 'id'

### ISSUE THREAD

**Issue by S1SYPHOS** [mullema/k3-image-clip#1]
Hey there,
when creating an `image-clip` field, I get this error message: 

![image](https://user-images.githubusercontent.com/12161504/58456960-d04d2300-8125-11e9-9d67-26e10df3e792.png)

Any ideas how to fix this are appreciated!
Thanks for this plugin, can't wait to use it :+1:

**Comment by S1SYPHOS** [comment]
In the meantime I found the source of my troubles: the field's name was `cover`. When changing it to something else, the problem was gone.

Q: Is `cover` somehow reserved?

Have a good day,
S1SYPHOS

**Comment by S1SYPHOS** [comment]
Well, my problem persists, and it might be even harder to debug:
Now, I enter an image, save the page, visit another page, and **everytime I come back**, the field has the error shown above. When I change the field name once more, reload the page: I can select an image again! But, when saving, leaving the page, coming back: again, *Illegal offset error* ..

**Comment by S1SYPHOS** [comment]
See [this discussion](https://forum.getkirby.com/t/plugin-k3-image-clip-illegal-string-offset-id/14398/4) on the forum:
Any chance to convert the 'normal' `files` type content to your 'id' based full path format?

**Comment by mullema** [comment]
@S1SYPHOS I am not able to reproduce your problem here:

> In the meantime I found the source of my troubles: the field's name was cover. When changing it to something else, the problem was gone.

Could you give me some more information over here: https://github.com/mullema/k3-image-clip/issues/4
