### ISSUE TITLE
Problem when using field in the site blueprint

### ISSUE THREAD

**Issue by lumpysimon** [mullema/k3-image-clip#15]
If I add an `image-clip` field to the `site.yml` blueprint the cropped image does not update. This is similar to https://github.com/mullema/k3-image-clip/issues/14 except the request in this case is returning a 404 error as it's looking for a non-existent file in the media folder.

The file being requested is `https://simon.test/sites/simon/media/pages/home/89ea76900d-0/fuj1234-simon-1408x-clip443x442-373x668.jpg`, the correct path should be `https://simon.test/sites/simon/media/site/...`

<img width="1035" alt="Screenshot 2021-02-19 at 12 34 45" src="https://user-images.githubusercontent.com/625372/108505341-21fcf000-72af-11eb-828a-d7492aba5e73.png">

**Comment by mullema** [comment]
What Kirby and Plugin Version are you using?

**Comment by lumpysimon** [comment]
Kirby 3.5.3
Image Clip: I've installed the plugin as a git submodule, so it's the latest version of the master branch
