### ISSUE TITLE
Refreshing content

### ISSUE THREAD

**Issue by grommas** [mullema/k3-image-clip#2]
Hi Matthias

Thank you for the Plugin, exactly what I was looking for! Following problem: If I use it as a 'normal' field, everything is working somehow. I can crop the image, save the page, everything is fine. Except of my local environment, integrated in a webpack workflow with browsersync etc. I got some errors showing up for some miliseconds, before everything gets refreshed. The biggest problem: If I use it on a structure field inside a structure field, it’s not working at all. Even if I test it on the server. Do you know why this is happening? Any ideas for a solution? Looking forward hearing from you.

Cheers, Jakob

**Comment by mullema** [comment]
Hi Jakob

Thank you for your feedback. 
Could you post here what the error message in your webpack-browsersync setup says?

**Comment by grommas** [comment]
On the panel page, there is following error message inside my Files field:
```
**The Section 'Files' could not be loaded.** 
NetworkError when attempting to fetch resource.
```
There is no log or error in my setup. And it’s the same behavior on my server.

**Comment by mullema** [comment]
Hi Jakob
In the develop branch you'll find a version that should fix the issue with structure fields. I think this could also be the fix for your browsersync problem. Would you please give it a try?
It was tested with Kirby 3.2.5rc2

**Comment by grommas** [comment]
Hi Matthias 
got back to the project and tested it. It works, thanks a lot!
