### ISSUE TITLE
TypeError with Kirby 3.7

### ISSUE THREAD

**Issue by pironmaurice** [mullema/k3-image-clip#24]
There is a bug with Kirby 3.7.

If an image does not have any crop settings, a TypeError follows: 

<img width="422" alt="Bildschirmfoto 2022-07-12 um 12 20 28" src="https://user-images.githubusercontent.com/58592014/178469910-e4e40a35-cded-4160-bedb-0efa368b76fa.png">

**Comment by mullema** [comment]
Hi @pironmaurice
Are you using version 3.1.1?

**Comment by pironmaurice** [comment]
Hey @mullema 

When updating to Kirby 3.7, composer also updated the plugin. This error appears with version 3.1.0 of the k3-image-clip plugin. After a downgrade to 3.0, it works again.

**Comment by mullema** [comment]
Did you try to upgrade to 3.1.1? This should solve the problem
