### ISSUE TITLE
Clip-Modal closes when dragging size out of modal

### ISSUE THREAD

**Issue by lareusmedia** [mullema/k3-image-clip#5]
As the title already said, if i drag one of the edges out of the modal, the modal closes automatically. Thats to be honest quite annoying. Could this possibly be fixed somehow?

**Comment by mullema** [comment]
Hi!
Thank you for your feedback.

I am not sure whether I understand correctly what problem you are describing. It should not be possible to move the edges out of the picture.

What is your browser/OS/Kirby Version?
