### ISSUE TITLE
Wrong sizes using minwidth minheight with portrait format clip 

### ISSUE THREAD

**Issue by Pandorrrrrra** [mullema/k3-image-clip#6]
Hey Matthias, really great plugin !

I run into an issue trying it out:

**Description**
Setting a clip using minwidth and minheight with portrait format, the image size is wrong. Scaling the selection on the image, the selected area also snaps to a narrower area if the minimum is reached. Independent from the selection size, the image ratio is not always exact.

**To Reproduce**
1. Use the following blueprint options:

```
clip:
 minwidth: 275
 minheight: 315
 ratio: fixed
```
2. Scale the selection on the image to the smallest size
3. The selected are snaps to a narrower area
4. Check the cropped image an compare the sizes: blueprint = 275 * 315, image = 274 * 360

**Expected behavior**
The image size should be 275 * 315.
If the 274 instead of 275 has to do with rounding, maybe it could just round to the values of the blueprint (275) ?

**Kirby Version**
3.2.3

**Desktop**
macOS Sierra 10.12.6
Firefox 68.0.1
Chrome 76.0

**Comment by mullema** [comment]
- [x] keep min size when hitting border
- [x] ratio calculation with positive ratio
- [ ] rounding error
