### ISSUE TITLE
Files section support

### ISSUE THREAD

**Issue by jobdr** [mullema/k3-image-clip#8]
Hi Matthias,

It seems that there is no support for the files section.
https://getkirby.com/docs/reference/panel/sections/files

Is such a development planned ?

Thank you for this plugin ! :)

**Comment by mullema** [comment]
Hi @jobdr 
Thank you for your request. The image-clip-field is a field, as it's name says and therefore not integrated into a files section. I could think about a combination of files-field and options / dialog in the files section. 

What would be your use case for this?
