### ISSUE TITLE
Invalid section type ("image-clip")

### ISSUE THREAD

**Issue by OneMohrTime** [mullema/k3-image-clip#9]
Good news of the issue: the frontend templates are working exactly as expected. I've also got a [kirby-timber](https://github.com/mgfagency/kirby-twig) setup, and it seems to have complete compatibility.

Bad news: switching `file` to `image-clip` doesn't render in the panel locally. I'm running v2.3.5, and have a `files/image-clip.yml` blueprint with the contents from the example on the [README](https://github.com/mullema/k3-image-clip#panel-usage), and installed with composer. From what I can tell in the readme, that should be enough to switch `file` to `image-clip`. Did I miss a step?

<img width="835" alt="Screen Shot 2019-11-03 at 21 52 22" src="https://user-images.githubusercontent.com/11075805/68097524-7d6e5900-fe85-11e9-8811-ac2016e6e7c8.png">

**Comment by mullema** [comment]
@OneMohrTime the field requires at least Kirby 3.2
Also remember it is a *field* not a section

**Comment by OneMohrTime** [comment]
@mullema I mistyped - meant 3.2.5, not 2.3.5. And that totally makes sense 🤦‍♂ long, late night coding session loses again.
